services:
  server:
    platform: linux/arm64
    hostname: server
    container_name: server
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
      target: local
      args:
        ENV: local
        WORK_DIR: /workdir
        INSTALL_DIR: /opt/install
    ports:
      - "8001:8001"
    volumes:
      - .:/workdir
    networks:
      - server
    command: >
      bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload"

networks:
  server:
    name: crawl-server
    driver: bridge

