services:
  crawler:
    platform: linux/arm64
    hostname: crawler
    container_name: crawler
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
      target: local
      args:
        ENV: local
        WORK_DIR: /workdir
        INSTALL_DIR: /opt/install
    ports:
      - "8001:8000"
    volumes:
      - .:/workdir
    networks:
      - crawler
    command: >
      bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

networks:
  crawler:
    name: crawler
    driver: bridge

